name: encrypt decrypt file
on: push
jobs:
    decrypt:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   name: Decrypt file
                run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/index.php index.php.gpg

                env:
                    PASSPHRASE: ${{secrets.PASSPHRASE}}
            -   name: Print out file content
                run: cat $HOME/index.php